import {
  BriefcaseBusinessIcon,
  Watch,
  Paintbrush2,
  Lamp,
  SmartphoneIcon,
  CarFront,
  HomeIcon,
  DrillIcon,
  Monitor,
  Laptop,
  Bike,
  Car,
  TabletSmartphoneIcon,
  WashingMachine,
  Wine,
  Wrench,
  Cake,
  Shirt,
  Gem,
  TabletIcon,
  HeadphonesIcon,
  BuildingIcon,
  Building2Icon,
  SchoolIcon,
} from "lucide-react";

const CategoryIconsMd = {
  real_estate_parent_icon: <HomeIcon size={28} className="stroke-[1px]" />,
  vehicles_parent_icon: <CarFront size={28} className="stroke-[1px]" />,
  electronic_devices_parent_icon: <SmartphoneIcon size={28} className="stroke-[1px]" />,
  home_kitchen_parent_icon: <Lamp size={28} className="stroke-[1px]" />,
  services_parent_icon: <Paintbrush2 size={28} className="stroke-[1px]" />,
  personal_parent_icon: <Watch size={28} className="stroke-[1px]" />,
  tools_materials_equipment_parent_icon: <DrillIcon size={28} className="stroke-[1px]" />,
  jobs_parent_icon: <BriefcaseBusinessIcon size={28} className="stroke-[1px]" />,
  monitor_icon: <Monitor size={28} className="stroke-[1px]" />,
  laptop_icon: <Laptop size={28} className="stroke-[1px]" />,
  motor_cycle_icon: <Bike size={28} className="stroke-[1px]" />,
  car_icon: <Car size={28} className="stroke-[1px]" />,
  mobile_tablet_icon: <TabletSmartphoneIcon size={28} className="stroke-[1px]" />,
  electronic_home_appliance_icon: <WashingMachine size={28} className="stroke-[1px]" />,
  plate_glass_icon: <Wine size={28} className="stroke-[1px]" />,
  cycle_car_service: <Wrench size={28} className="stroke-[1px]" />,
  serving_service: <Cake size={28} className="stroke-[1px]" />,
  clothes_icons: <Shirt size={28} className="stroke-[1px]" />,
  gem_icon: <Gem size={28} className="stroke-[1px]" />,
  tablet_icon: <TabletIcon size={28} className="stroke-[1px]" />,
  mobile_accessory: <HeadphonesIcon size={28} className="stroke-[1px]" />,
  building_icon: <BuildingIcon size={28} className="stroke-[1px]" />,
  rend_building_icon: <Building2Icon size={28} className="stroke-[1px]" />,
  buy_building_icon: <SchoolIcon size={28} className="stroke-[1px]" />,
};
export const CategoryIconsSm = {
  real_estate_parent_icon: <HomeIcon size={24} className="stroke-[1px]" />,
  vehicles_parent_icon: <CarFront size={24} className="stroke-[1px]" />,
  electronic_devices_parent_icon: <SmartphoneIcon size={24} className="stroke-[1px]" />,
  home_kitchen_parent_icon: <Lamp size={24} className="stroke-[1px]" />,
  services_parent_icon: <Paintbrush2 size={24} className="stroke-[1px]" />,
  personal_parent_icon: <Watch size={24} className="stroke-[1px]" />,
  tools_materials_equipment_parent_icon: <DrillIcon size={24} className="stroke-[1px]" />,
  jobs_parent_icon: <BriefcaseBusinessIcon size={24} className="stroke-[1px]" />,
  monitor_icon: <Monitor size={24} className="stroke-[1px]" />,
  laptop_icon: <Laptop size={24} className="stroke-[1px]" />,
  motor_cycle_icon: <Bike size={24} className="stroke-[1px]" />,
  car_icon: <Car size={24} className="stroke-[1px]" />,
  mobile_tablet_icon: <TabletSmartphoneIcon size={24} className="stroke-[1px]" />,
  electronic_home_appliance_icon: <WashingMachine size={24} className="stroke-[1px]" />,
  plate_glass_icon: <Wine size={24} className="stroke-[1px]" />,
  cycle_car_service: <Wrench size={24} className="stroke-[1px]" />,
  serving_service: <Cake size={24} className="stroke-[1px]" />,
  clothes_icons: <Shirt size={24} className="stroke-[1px]" />,
  gem_icon: <Gem size={24} className="stroke-[1px]" />,
  tablet_icon: <TabletIcon size={24} className="stroke-[1px]" />,
  mobile_accessory: <HeadphonesIcon size={24} className="stroke-[1px]" />,
  building_icon: <BuildingIcon size={24} className="stroke-[1px]" />,
  rend_building_icon: <Building2Icon size={24} className="stroke-[1px]" />,
  buy_building_icon: <SchoolIcon size={24} className="stroke-[1px]" />,
};
export const CategoryIconsXs = {
  real_estate_parent_icon: <HomeIcon size={20} className="stroke-[1px]" />,
  vehicles_parent_icon: <CarFront size={20} className="stroke-[1px]" />,
  electronic_devices_parent_icon: <SmartphoneIcon size={20} className="stroke-[1px]" />,
  home_kitchen_parent_icon: <Lamp size={20} className="stroke-[1px]" />,
  services_parent_icon: <Paintbrush2 size={20} className="stroke-[1px]" />,
  personal_parent_icon: <Watch size={20} className="stroke-[1px]" />,
  tools_materials_equipment_parent_icon: <DrillIcon size={20} className="stroke-[1px]" />,
  jobs_parent_icon: <BriefcaseBusinessIcon size={20} className="stroke-[1px]" />,
  monitor_icon: <Monitor size={20} className="stroke-[1px]" />,
  laptop_icon: <Laptop size={20} className="stroke-[1px]" />,
  motor_cycle_icon: <Bike size={20} className="stroke-[1px]" />,
  car_icon: <Car size={20} className="stroke-[1px]" />,
  mobile_tablet_icon: <TabletSmartphoneIcon size={20} className="stroke-[1px]" />,
  electronic_home_appliance_icon: <WashingMachine size={20} className="stroke-[1px]" />,
  plate_glass_icon: <Wine size={20} className="stroke-[1px]" />,
  cycle_car_service: <Wrench size={20} className="stroke-[1px]" />,
  serving_service: <Cake size={20} className="stroke-[1px]" />,
  clothes_icons: <Shirt size={20} className="stroke-[1px]" />,
  gem_icon: <Gem size={20} className="stroke-[1px]" />,
  tablet_icon: <TabletIcon size={20} className="stroke-[1px]" />,
  mobile_accessory: <HeadphonesIcon size={20} className="stroke-[1px]" />,
  building_icon: <BuildingIcon size={20} className="stroke-[1px]" />,
  rend_building_icon: <Building2Icon size={20} className="stroke-[1px]" />,
  buy_building_icon: <SchoolIcon size={20} className="stroke-[1px]" />,
};
export default CategoryIconsMd;
