import {
  BriefcaseBusinessIcon,
  Watch,
  Paintbrush2,
  Lamp,
  SmartphoneIcon,
  CarFront,
  HomeIcon,
  Users,
  Gamepad,
  DrillIcon,
  Monitor,
  Laptop,
  Bike,
  Car,
  TabletSmartphoneIcon,
  WashingMachine,
  Wine,
  Wrench,
  Cake,
  Shirt,
  Gem,
  TabletIcon,
  HeadphonesIcon,
  BuildingIcon,
  Building2Icon,
  SchoolIcon,
} from "lucide-react";

const CategoryIconsMd = {
  real_estate_parent_icon: <HomeIcon size={20} />,
  vehicles_parent_icon: <CarFront size={20} />,
  electronic_devices_parent_icon: <SmartphoneIcon size={20} />,
  home_kitchen_parent_icon: <Lamp size={20} />,
  services_parent_icon: <Paintbrush2 size={20} />,
  personal_parent_icon: <Watch size={20} />,
  leisure_hobbies_parent_icon: <Gamepad size={20} />,
  community_parent_icon: <Users size={18} />,
  tools_materials_equipment_parent_icon: <DrillIcon size={18} />,
  jobs_parent_icon: <BriefcaseBusinessIcon size={18} />,
  monitor_icon: <Monitor size={18} />,
  laptop_icon: <Laptop size={18} />,
  motor_cycle_icon: <Bike size={18} />,
  car_icon: <Car size={18} />,
  mobile_tablet_icon: <TabletSmartphoneIcon size={18} />,
  electronic_home_appliance_icon: <WashingMachine size={18} />,
  plate_glass_icon: <Wine size={18} />,
  cycle_car_service: <Wrench size={18} />,
  serving_service: <Cake size={18} />,
  clothes_icons: <Shirt size={18} />,
  gem_icon: <Gem size={18} />,
  tablet_icon: <TabletIcon size={18} />,
  mobile_accessory: <HeadphonesIcon size={18} />,
  building_icon: <BuildingIcon size={18} />,
  rend_building_icon: <Building2Icon size={18} />,
  buy_building_icon: <SchoolIcon size={18} />,
};
export const CategoryIconsSm = {
  real_estate_parent_icon: <HomeIcon size={16} />,
  vehicles_parent_icon: <CarFront size={16} />,
  electronic_devices_parent_icon: <SmartphoneIcon size={16} />,
  home_kitchen_parent_icon: <Lamp size={16} />,
  services_parent_icon: <Paintbrush2 size={16} />,
  personal_parent_icon: <Watch size={16} />,
  leisure_hobbies_parent_icon: <Gamepad size={16} />,
  community_parent_icon: <Users size={16} />,
  tools_materials_equipment_parent_icon: <DrillIcon size={16} />,
  jobs_parent_icon: <BriefcaseBusinessIcon size={16} />,
  monitor_icon: <Monitor size={16} />,
  laptop_icon: <Laptop size={16} />,
  motor_cycle_icon: <Bike size={16} />,
  car_icon: <Car size={16} />,
  mobile_tablet_icon: <TabletSmartphoneIcon size={16} />,
  electronic_home_appliance_icon: <WashingMachine size={16} />,
  plate_glass_icon: <Wine size={16} />,
  cycle_car_service: <Wrench size={16} />,
  serving_service: <Cake size={16} />,
  clothes_icons: <Shirt size={16} />,
  gem_icon: <Gem size={16} />,
  tablet_icon: <TabletIcon size={16} />,
  mobile_accessory: <HeadphonesIcon size={16} />,
};
export default CategoryIconsMd;
